version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - "5432:5432"  # Puerto 5432 expuesto
    environment:
      POSTGRES_USER: ${POSTGRES_USER}          # Usando la variable del archivo .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Usando la variable del archivo .env
      POSTGRES_DB: ${POSTGRES_DB}              # Usando la variable del archivo .env
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistencia de datos
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
